### PR TITLE
Handle empty responses (no snow depth observations)

### PR DESCRIPTION
**Pull request by emiliom**
Addresses #8 

Also, increment version, improved the snow_data docstring, tweaked the README for consistency with docstring changes, and added explict conda channels to environment.yml

### CODE REVIEW

**Comment by emiliom** [comment]
@aaarendt Here's the fix for #8. I've tested it. If the API call doesn't return any observations, `snow_data` will return `None` plus a very brief run-time message.

See what you think.

**Comment by aaarendt** [comment]
@emiliom I discovered by chance another case that slips past your error checking:

```python
obs = mh.snow_data(limit=10000, start=datetime(2017,8,1), end=datetime(2017,9,1), bbox=region)
```

This returns an empty data frame with no printing of the error condition. That is because there is a record but it contains `snow_depth = None`.

So I think this needs an additional check just before returning the dataframe, something like:

```python
if obs['snow_depth'].isnull:
   print("Results found but not containing snow depth data")
   return None
```

**Comment by emiliom** [comment]
Thanks! Can you share here the region you're using that surfaces this case? That'll help me develop and test the error catching. I'll try to address this tomorrow.

**Comment by aaarendt** [comment]
It's all of the lower 48 states:

```python
region = {
    'latmax' : 50,
    'latmin' : 25,
    'lonmax': -65,
    'lonmin': -125,
}
```

**Comment by emiliom** [comment]
Ah. Thanks

**Comment by emiliom** [comment]
@aaarendt I've pushed a commit that adds error catching for the situation you identified. That case now returns a `None` and this run-time message: "No snow_depth results found."

**Review by aaarendt — APPROVED** [review]

**Pull request merged**
